version: '3'
services:
  goldenphp:
    image: chatbot-goldenphp:latest
    build:
      context: ./goldenphp
      dockerfile: Dockerfile
      args:
        - "APP_ENV=dev"
        - "APP_DEBUG=1"
        - "SWOOLE_VERSION=5.1.0"
        - "XDEBUG_VERSION=3.2.2"
  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    env_file:
      - ./backend/.env
    environment:
      AUTORELOAD_PROGRAMS: "app-swoole"
      AUTORELOAD_ANY_FILES: 0
      DISABLE_DEFAULT_SERVER: 1
    ports:
      - "80:80"
      - "8591:9000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - default
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatbot
      MYSQL_USER: chatbot
      MYSQL_PASSWORD: chatbot
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    restart: always
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
        - "4200:4200"
    volumes:
        - ./frontend:/app

networks:
    default:
        name: chatbot

volumes:
  mysql:
    name: chatbot-mysql
