version: '3'
services:
  backend:
    build: ./backend/.docker
    environment:
      AUTORELOAD_PROGRAMS: "app-swoole"
      AUTORELOAD_ANY_FILES: 0
      DISABLE_DEFAULT_SERVER: 1
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html