<?php

namespace App\Domain\Assessment\Enums;

enum AssessmentStatusEnum: string
{
    case ASSESSMENT_START_SUCCESS = 'ASSESSMENT_START_SUCCESS';
    case ASSESSMENT_START_ERROR = 'ASSESSMENT_START_ERROR';
    case ASSESSMENT_IN_PROGRESS = 'ASSESSMENT_IN_PROGRESS';
    case ASSESSMENT_RECEIVE_USER_INPUT_SUCCESS = 'ASSESSMENT_RECEIVE_USER_INPUT_SUCCESS';
    case ASSESSMENT_RECEIVE_USER_INPUT_ERROR = 'ASSESSMENT_RECEIVE_USER_INPUT_ERROR';
    case ASSESSMENT_GENERATE_OUTPUT_SUCCESS = 'ASSESSMENT_GENERATE_OUTPUT_SUCCESS';
    case ASSESSMENT_GENERATE_OUTPUT_ERROR = 'ASSESSMENT_GENERATE_OUTPUT_ERROR';
    case ASSESSMENT_COMPLETE_SUCCESS = 'ASSESSMENT_COMPLETE_SUCCESS';
    case ASSESSMENT_COMPLETE_ERROR = 'ASSESSMENT_COMPLETE_ERROR';
}
